# This is a basic workflow to help you get started with Actions

name: Lint

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ ros2, ros2-devel, galactic-devel ]
  pull_request:
    branches: [ ros2, ros2-devel, galactic-devel ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  ament_lint_galactic:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        linter: [copyright, cppcheck, cpplint, flake8, pep257, xmllint]
        distribution: [galactic]
    steps:
      - uses: actions/checkout@v1
      - uses: ros-tooling/setup-ros@0.2.1
      - uses: ros-tooling/action-ros-lint@v0.1
        with:
          distribution: ${{ matrix.distribution }}
          linter: ${{ matrix.linter }}
          package-name: 
            turtlebot3_simulations
            turtlebot3_fake_node
            turtlebot3_gazebo
